//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheetah.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAero {
            get {
                return ((bool)(this["UseAero"]));
            }
            set {
                this["UseAero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNavBar {
            get {
                return ((bool)(this["ShowNavBar"]));
            }
            set {
                this["ShowNavBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gt-web-software.webs.com/")]
        public string Homepage {
            get {
                return ((string)(this["Homepage"]));
            }
            set {
                this["Homepage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool checkForUpdatesOnStart {
            get {
                return ((bool)(this["checkForUpdatesOnStart"]));
            }
            set {
                this["checkForUpdatesOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open default")]
        public string startpage {
            get {
                return ((string)(this["startpage"]));
            }
            set {
                this["startpage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customstartpage {
            get {
                return ((string)(this["customstartpage"]));
            }
            set {
                this["customstartpage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
        <?xml version=""1.0"" encoding=""utf-16""?>
        <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
        <string>www.redtube.com</string>
        <string>www.playboy.com</string>
        <string>www.coedcherry.com</string>
        <string>www.tokyoteenis.com</string>
        <string>www.crocoporn.com</string>
        <string>www.semprot.com</string>
        <string>www.ideal-teens.com</string>
        <string>www.japanwhore.com</string>
        <string>www.sukatoro.com</string>
        <string>www.karupshax.com</string>
        <string>www.perfectasianpussy.com</string>
        <string>www.nippon-idols.com</string>
        <string>www.69idols.com</string>
        <string>www.150teengalleries.com</string>
        <string>www.digitaldesire.com</string>
        <string>www.ceritasex.cn</string>
        <string>www.tiava.com</string>
        <string>www.xnxx.com</string>
        </ArrayOfString>
      ")]
        public global::System.Collections.Specialized.StringCollection BlockedWebsites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlockedWebsites"]));
            }
            set {
                this["BlockedWebsites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockPopup {
            get {
                return ((bool)(this["BlockPopup"]));
            }
            set {
                this["BlockPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DontShowWarningBox {
            get {
                return ((bool)(this["DontShowWarningBox"]));
            }
            set {
                this["DontShowWarningBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool deletecookies {
            get {
                return ((bool)(this["deletecookies"]));
            }
            set {
                this["deletecookies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string browsermode {
            get {
                return ((string)(this["browsermode"]));
            }
            set {
                this["browsermode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool loadimage {
            get {
                return ((bool)(this["loadimage"]));
            }
            set {
                this["loadimage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usejavascript {
            get {
                return ((bool)(this["usejavascript"]));
            }
            set {
                this["usejavascript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool usecache {
            get {
                return ((bool)(this["usecache"]));
            }
            set {
                this["usecache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool allowplugins {
            get {
                return ((bool)(this["allowplugins"]));
            }
            set {
                this["allowplugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool allowcookies {
            get {
                return ((bool)(this["allowcookies"]));
            }
            set {
                this["allowcookies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sourceallignment {
            get {
                return ((string)(this["sourceallignment"]));
            }
            set {
                this["sourceallignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sourcewidth {
            get {
                return ((string)(this["sourcewidth"]));
            }
            set {
                this["sourcewidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sourcethickness {
            get {
                return ((string)(this["sourcethickness"]));
            }
            set {
                this["sourcethickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sourceshadding {
            get {
                return ((string)(this["sourceshadding"]));
            }
            set {
                this["sourceshadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string sourcecolor {
            get {
                return ((string)(this["sourcecolor"]));
            }
            set {
                this["sourcecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sourcepercentorpixel {
            get {
                return ((string)(this["sourcepercentorpixel"]));
            }
            set {
                this["sourcepercentorpixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        <?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n        <ArrayOfString xmlns:x" +
            "si=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001" +
            "/XMLSchema\">\r\n        <string />\r\n        </ArrayOfString>\r\n      ")]
        public global::System.Collections.Specialized.StringCollection Bookmark {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Bookmark"]));
            }
            set {
                this["Bookmark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open Praken Home")]
        public string NewTab {
            get {
                return ((string)(this["NewTab"]));
            }
            set {
                this["NewTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomNewTab {
            get {
                return ((string)(this["CustomNewTab"]));
            }
            set {
                this["CustomNewTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool deletecache {
            get {
                return ((bool)(this["deletecache"]));
            }
            set {
                this["deletecache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VisPanel {
            get {
                return ((bool)(this["VisPanel"]));
            }
            set {
                this["VisPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskDownloadLoc {
            get {
                return ((bool)(this["AskDownloadLoc"]));
            }
            set {
                this["AskDownloadLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Downloadloc {
            get {
                return ((string)(this["Downloadloc"]));
            }
            set {
                this["Downloadloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google")]
        public string SearchEngine {
            get {
                return ((string)(this["SearchEngine"]));
            }
            set {
                this["SearchEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockAdv {
            get {
                return ((bool)(this["BlockAdv"]));
            }
            set {
                this["BlockAdv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteBookmark {
            get {
                return ((bool)(this["DeleteBookmark"]));
            }
            set {
                this["DeleteBookmark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteHistory {
            get {
                return ((bool)(this["DeleteHistory"]));
            }
            set {
                this["DeleteHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFull {
            get {
                return ((bool)(this["ShowFull"]));
            }
            set {
                this["ShowFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SecurityLevel {
            get {
                return ((int)(this["SecurityLevel"]));
            }
            set {
                this["SecurityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopupOpenInWindow {
            get {
                return ((bool)(this["PopupOpenInWindow"]));
            }
            set {
                this["PopupOpenInWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
        <?xml version=""1.0"" encoding=""utf-16""?>
        <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
        <string>show_ads.js</string>
        <string>ads.sittiad</string>
        <string>ads.clicksor</string>
        <string>.kliksaya.com</string>
        <string>adsensecamp</string>
        <string>ads.ad4game</string>
        <string>pagead2.</string>
        <string>googleadservices</string>
        <string>ads.lycos.com</string>
        <string>ad-emea</string>
        <string>adbanner</string>
        <string>scripts.lycos.com</string>
        <string>/ad/</string>
        <string>ad.yieldmanager</string>
        <string>googleads</string>
        </ArrayOfString>
      ")]
        public global::System.Collections.Specialized.StringCollection AdsFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdsFilter"]));
            }
            set {
                this["AdsFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PopupException {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PopupException"]));
            }
            set {
                this["PopupException"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int newtabaction {
            get {
                return ((int)(this["newtabaction"]));
            }
            set {
                this["newtabaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string newtabcustompage {
            get {
                return ((string)(this["newtabcustompage"]));
            }
            set {
                this["newtabcustompage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool smoothscrolling {
            get {
                return ((bool)(this["smoothscrolling"]));
            }
            set {
                this["smoothscrolling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string custompluginspath {
            get {
                return ((string)(this["custompluginspath"]));
            }
            set {
                this["custompluginspath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool allowinsecure {
            get {
                return ((bool)(this["allowinsecure"]));
            }
            set {
                this["allowinsecure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool javascriptclipboard {
            get {
                return ((bool)(this["javascriptclipboard"]));
            }
            set {
                this["javascriptclipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool javascriptwindows {
            get {
                return ((bool)(this["javascriptwindows"]));
            }
            set {
                this["javascriptwindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool webgl {
            get {
                return ((bool)(this["webgl"]));
            }
            set {
                this["webgl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool webaudio {
            get {
                return ((bool)(this["webaudio"]));
            }
            set {
                this["webaudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool websecurity {
            get {
                return ((bool)(this["websecurity"]));
            }
            set {
                this["websecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomContext {
            get {
                return ((bool)(this["CustomContext"]));
            }
            set {
                this["CustomContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.6 (KHTML, like Gecko) Cheetah" +
            "/1.0.0.0 Chrome/20.0.1092.0 Safari/536.6")]
        public string Useragent {
            get {
                return ((string)(this["Useragent"]));
            }
            set {
                this["Useragent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cheetah")]
        public string defaultua {
            get {
                return ((string)(this["defaultua"]));
            }
            set {
                this["defaultua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iso-8859-1")]
        public string Encoding {
            get {
                return ((string)(this["Encoding"]));
            }
            set {
                this["Encoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SavePassLogin {
            get {
                return ((bool)(this["SavePassLogin"]));
            }
            set {
                this["SavePassLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PassLogin {
            get {
                return ((string)(this["PassLogin"]));
            }
            set {
                this["PassLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{default}")]
        public string DownloadsFolder {
            get {
                return ((string)(this["DownloadsFolder"]));
            }
            set {
                this["DownloadsFolder"] = value;
            }
        }
    }
}
